# Site settings
title: LightSAML
email: lightsaml@gmail.com
description: LightSAML PHP libraries for SAML and Symfony bundles
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lightsaml.com" # the base hostname & protocol for your site
twitter_username: lightsaml
github_username:  lightsaml

highlighter: rouge

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap

breadcrumbs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            category: "blog"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
